backend:
  name: github
  repo: https://github.com/lesley-2198/bongiwe_porfolio
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  auth_scope: repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "research"
    label: "Research Papers"
    folder: "content/research"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "PDF File", name: "file", widget: "file", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
